version: '3.7'

services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:8080"
    depends_on:
      - redismod
    environment:
      SPRING_REDIS_HOST: redismod
      STOMP_PORT: 80

  redismod:
    image: redislabs/redismod
    hostname: redismod
    container_name: redismod
    restart: always
    ports:
      - "6379:6379"
