name: Build
true:
  pull_request: null
jobs:
  build:
    name: Build
    if: startsWith(github.event.head_commit.message, 'Releasing version') != true
    runs-on: ubuntu-latest
    steps:
    - name: Build
      uses: redis-field-engineering/redis-build-action@v1